
1. 为什么需要手动抛出异常？
在实际开发中，如果出现不满足具体场景的代码问题，
我们就有必要手动抛出一个指定类型的异常对象。


2. 如何理解"自动 vs 手动"抛出异常对象？

过程1：“抛”
    "自动抛"： 程序在执行的过程中，一旦出现异常，就会在出现异常的代码处，生成对应异常类的对象，并将对象抛出。
    一旦抛出，此程序就不会执行其后的代码了。

    ”手动抛“：程序在执行的过程中，不满足指定条件的情况下，我们主动的使用”throw + 异常类的对象“ 抛出异常对象

过程2：“抓”
    狭义上讲： try--catch--finally 的方式捕获处理
    广义上讲： 把“抓”理解为处理，则此时对应这异常处理的两种方式：①try--catch--finally
                                                        ② throws

throw：是用来产生异常
throws：是用来处理异常

3. 如何实现手动抛出异常？
在方法内部满足指定条件的情况下使用 “throw new 异常类型对象”的方式抛出。


4. 注意点：throw后的代码不能被执行，编译不通过。

